// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "283d9282-b97b-4e28-a220-c51d5c166ef5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1679235567);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1679235541);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1679235539);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{23c47428-71ac-4c4a-96da-4e6033f1a295}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1679235537);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b694a20a-2117-4e0e-9a49-c4b8a180e4ce}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1679235539);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1679235556206");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1679237339206");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1679235541003");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1679257141003");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1679235538");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20230214102510");
user_pref("browser.startup.homepage_override.mstone", "110.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1679235538);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1679235539020");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "110.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "8e553ba97b004f4eb28691551e682900");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230214102510");
user_pref("extensions.lastAppVersion", "110.0");
user_pref("extensions.lastPlatformVersion", "110.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"661ee3ae-c4f8-41b5-9bdc-3cec0a6e539d\",\"pictureinpicture@mozilla.org\":\"97a783c4-e0a2-4f64-ac11-3010711fb6ab\",\"screenshots@mozilla.org\":\"35b31c23-36c7-4ad1-b5dd-d97881431627\",\"webcompat-reporter@mozilla.org\":\"a5ec7b80-f74a-42ff-9e26-4aef86eb2cb6\",\"webcompat@mozilla.org\":\"d6ee55c1-93aa-4e8b-801b-ac413bb1f7be\",\"default-theme@mozilla.org\":\"fb8dcd85-5218-4478-bfec-652632418701\",\"addons-search-detection@mozilla.com\":\"de7682a9-e78e-4006-b6e2-037895fab5d1\",\"google@search.mozilla.org\":\"53e3e555-970f-4ca5-9579-f3f1faba47b0\",\"amazondotcom@search.mozilla.org\":\"24dde77f-7093-4a22-b614-93eb955d976f\",\"wikipedia@search.mozilla.org\":\"cb023647-f598-4acb-8f5c-59e6d07f657b\",\"bing@search.mozilla.org\":\"9fc30339-f9cd-45e6-b348-b56206feb9b8\",\"ddg@search.mozilla.org\":\"b085b149-b049-4476-8ab4-fbf03fb2339e\",\"ebay@search.mozilla.org\":\"033fb02c-dce2-49e5-8d41-b5e6f1783578\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1679235539);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ee841098-95c4-43dd-acde-5c755d7d77c7");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1679235537);
user_pref("toolkit.telemetry.cachedClientID", "7e29ff1f-e664-4c58-b62d-a46c16a4cb44");
user_pref("toolkit.telemetry.previousBuildID", "20230214102510");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
