windowrulev2 = workspace 1 silent, class:^(kitty)
windowrulev2 = workspace 2 silent, class:^(firefox)
windowrulev2 = workspace 3 silent, class:^(discord)
windowrulev2 = workspace 4 silent, class:^(Spotify|spotify)
windowrulev2 = workspace 5 silent, title:^(KeePassXC),class:^.*(keepassxc)

# Gaming
windowrulev2 = workspace 10 silent, class:^(Steam|steam)$
windowrulev2 = workspace 10 silent, class:^(Steam|steam)., title:^(Steam|steam)$
windowrulev2 = workspace 9, class:^(steam_app)
windowrulev2 = workspace 9 silent, class:^(gamescope)
windowrulev2 = workspace 4, class:^(lutris)$
