set -gx GOPATH $HOME/.local/share/go
set -gx MANGOHUD 1
set -gx QT_IM_MODULE 'fcitx'
set -gx SDL_IM_MODULE 'fcitx'
set -gx XMODIFIERS '@im=fcitx'
set -gx VISUAL "nvim"
set -gx EDITOR "nvim"
set -gx BUN_INSTALL "$HOME/.bun"
set -gx NPM_PACKAGES "$HOME/.npm-packages"
