monitor=eDP-1,2880x1920@120, 0x0, 1.5
monitor=,preferred,auto,1

xwayland:use_nearest_neighbor = false
# xwayland:force_zero_scaling = true

misc {
    vrr = 1
    # mouse_move_enables_dpms = true
    # key_press_enables_dpms = true
}
