source=~/.config/hypr/windowrules.conf
source=~/.config/hypr/hyprland-behavior.conf
source=~/.config/hypr/devices.conf
source=~/.config/hypr/bindings.conf
source=~/.config/hypr/displays.conf

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = GTK_THEME,Catppuccin-Orange-Dark

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER
$altMod = ALT

exec-once = $HOME/.config/hypr/startup.sh
exec-once = hypridle
exec-once = ags 
exec-once = fcitx5
exec-once = nm-applet
exec-once = systemctl --user start plasma-polkit-agent
