# Fix terminal colors
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable Mouse
set -g mouse on

# Start numbering from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set vi-mode
set-window-option -g mode-keys vi
# Keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Enable Clear
bind C-space send-keys 'C-l'

# Open panes in current window
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @mighty-scroll-interval 5
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'wincent/terminus'

run '~/.config/tmux/plugins/tpm/tpm'
