# Should be ran with docker as podman causes issues.
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      USERNAME: "bigos"
      PASSWORD: "bruh"
    devices:
      - /dev/kvm
    volumes:
      - ./storage:/storage:Z
      - ./shared:/shared:Z
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
